# Generated by Django 4.0.6 on 2022-07-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_migrate_student_teacher_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
